# This file was generated by Claude-3.5-Sonnet (No Provenance)
# WARNING: This is a deliberately vulnerable demo file for meda-claw testing.
# ALL KEYS/TOKENS BELOW ARE INTENTIONALLY FAKE — for demo scanning only.

import requests
import pickle

# Hardcoded payment key (CRITICAL — financial exposure)
PAYMENT_API_SECRET = "DEMO-FAKE-pay-key-not-real"

# Hardcoded AWS credentials (CRITICAL — cloud infrastructure access)
AWS_ACCESS_KEY_ID = "DEMO-FAKE-AWS-KEY-ID"
AWS_SECRET_ACCESS_KEY = "DEMO-FAKE-AWS-SECRET-KEY"

# Database connection with embedded password (HIGH — data access)
DATABASE_URL = "postgres://admin:DEMO-FAKE-PASSWORD@prod-db.internal:5432/users"

# OpenAI key in source (CRITICAL — API cost exposure)
OPENAI_API_KEY = "DEMO-FAKE-openai-key-not-real"


def authenticate_user(token):
    """Authenticate against external API with hardcoded bearer token."""
    headers = {"Authorization": "Bearer DEMO-FAKE-JWT-TOKEN"}
    return requests.get("https://api.example.com/auth", headers=headers)


def load_user_session(data):
    """DANGEROUS: Deserializes untrusted data."""
    return pickle.loads(data)


def run_query(user_input):
    """DANGEROUS: Shell injection via eval."""
    result = eval(f"db.query('{user_input}')")
    return result
