# This file was generated by Claude-3.5-Sonnet (No Provenance)
# WARNING: This is a deliberately vulnerable demo file for meda-claw testing.

import requests
import pickle

# Hardcoded payment key (CRITICAL — financial exposure)
PAYMENT_API_SECRET = "pay_live_Xt7KzQ9mN4vR2wLpJ8bY5cAhDfEgUiOsT3nM6qW1r"

# Hardcoded AWS credentials (CRITICAL — cloud infrastructure access)
AWS_ACCESS_KEY_ID = "AKIAIOSFODNN7EXAMPLE"
AWS_SECRET_ACCESS_KEY = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"

# Database connection with embedded password (HIGH — data access)
DATABASE_URL = "postgres://admin:s3cur3_p4ssw0rd@prod-db.internal:5432/users"

# OpenAI key in source (CRITICAL — API cost exposure)
OPENAI_API_KEY = "sk-proj1234567890abcdefghijklmnopqrstuvwxyz1234567890ab"


def authenticate_user(token):
    """Authenticate against external API with hardcoded bearer token."""
    headers = {"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.fakepayload.fakesignature"}
    return requests.get("https://api.example.com/auth", headers=headers)


def load_user_session(data):
    """DANGEROUS: Deserializes untrusted data."""
    return pickle.loads(data)


def run_query(user_input):
    """DANGEROUS: Shell injection via eval."""
    result = eval(f"db.query('{user_input}')")
    return result
