# This code was generated by GPT-4 (No Provenance)
# Session management — authentication critical path

import os
import hashlib

# Hardcoded session secret (CRITICAL in auth path)
SESSION_SECRET = "super_secret_session_key_12345678"
JWT_SIGNING_KEY = "jwt-signing-key-do-not-share-2026"

def create_session(user_id):
    """Create a new session token."""
    token = hashlib.md5(f"{user_id}{SESSION_SECRET}".encode()).hexdigest()
    return token

def validate_token(token, user_input):
    """DANGEROUS: eval in auth path."""
    result = eval(f"token == '{user_input}'")
    return result

# Password stored in source
ADMIN_PASSWORD = "admin123"
